# Generated by Django 5.2.3 on 2025-06-30 00:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента/Название компании')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название шаблона')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('body', models.TextField(verbose_name='Тело письма (HTML/Plain text)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'Шаблон Email',
                'verbose_name_plural': 'Шаблоны Email',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание проекта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255, verbose_name='Раздел сметы')),
                ('justification', models.CharField(max_length=255, verbose_name='Обоснование (ТЦ/ФССЦ)')),
                ('item_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер по порядку')),
                ('item_name', models.TextField(verbose_name='Наименование')),
                ('unit', models.CharField(max_length=50, verbose_name='Ед. изм.')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена за ед.')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Всего')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_requests', to='main_app.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Элемент коммерческого запроса',
                'verbose_name_plural': 'Элементы коммерческих запросов',
                'ordering': ['project', 'section', 'item_number'],
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название рассылки')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отправки')),
                ('status', models.CharField(choices=[('Draft', 'Черновик'), ('Sending', 'Отправляется'), ('Sent', 'Отправлено'), ('Failed', 'Ошибка')], default='Draft', max_length=50, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('generated_word_file', models.FileField(blank=True, null=True, upload_to='generated_documents/', verbose_name='Сгенерированный документ Word')),
                ('processed_excel_file', models.FileField(blank=True, null=True, upload_to='processed_excels/', verbose_name='Обработанный Excel файл')),
                ('recipients', models.ManyToManyField(to='main_app.client', verbose_name='Получатели')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.emailtemplate', verbose_name='Использованный шаблон')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to='main_app.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Email рассылка',
                'verbose_name_plural': 'Email рассылки',
                'ordering': ['-sent_at'],
            },
        ),
    ]
